dist: trusty
language: java
sudo: false
jdk:
  - openjdk8
  - oraclejdk8
script:
  - sudo apt-get update
  - sudo apt-get install -y maven
  - export MAVEN_OPTS="-XX:MaxPermSize=128m"
  - mvn clean package -pl war -am -DskipTests -Dfindbugs.skip
  - ls -la war/target/