dist: trusty
language: java
sudo: false
env:
  - MVN_VERSION="3.6.1"
jdk:
  - openjdk8
  - oraclejdk8
before_install:
  - sudo apt-get purge -y maven
  - wget https://www-us.apache.org/dist/maven/maven-3/${MVN_VERSION}/binaries/apache-maven-${MVN_VERSION}-bin.tar.gz
  - sudo tar -zxf apache-maven-${MVN_VERSION}-bin.tar.gz -C /usr/local/
  - sudo mv /usr/local/maven-3.5.2/bin/mvn /usr/local/maven-3.5.2/bin/mvn_352
  - sudo ln -s /usr/local/apache-maven-${MVN_VERSION}/bin/mvn /usr/local/maven-3.5.2/bin/mvn
  - mvn -version
script:  
  - export MAVEN_OPTS="-XX:MaxPermSize=128m"
  - mvn clean package -pl war -am -DskipTests -Dfindbugs.skip
  - ls -la war/target/